export const skills = [
  {
    name: 'Vue',
    value: 'vue',
    icon: 'logos:vue',
    favorite: true,
    desc: 'The Progressive JavaScript Framework',
    url: 'https://vuejs.org',
  },
  {
    name: 'Nuxt',
    value: 'nuxt',
    icon: 'logos:nuxt-icon',
    favorite: true,
    desc: 'The Intuitive Web Framework',
    url: 'https://nuxt.com',
  },
  {
    name: 'TypeScript',
    value: 'typescript',
    icon: 'logos:typescript-icon',
    favorite: true,
    desc: 'JavaScript that scales',
    url: 'https://www.typescriptlang.org',
  },
  {
    name: 'Tailwind CSS',
    value: 'tailwindcss',
    icon: 'logos:tailwindcss-icon',
    favorite: true,
    desc: 'A utility-first CSS framework',
    url: 'https://tailwindcss.com',
  },
  {
    name: 'UnoCSS',
    value: 'unocss',
    icon: 'logos:unocss',
    favorite: true,
    desc: 'The instant on-demand atomic CSS engine',
    url: 'https://unocss.dev',
  },
  {
    name: 'TanStack Query',
    value: 'tanstack query',
    icon: 'logos:react-query-icon',
    favorite: true,
    desc: 'Powerful asynchronous state management',
    url: 'https://tanstack.com/query',
  },
  {
    name: 'Svelte',
    value: 'svelte',
    icon: 'logos:svelte-icon',
    favorite: true,
    desc: 'Cybernetically enhanced web apps',
    url: 'https://svelte.dev',
  },
  {
    name: 'React',
    value: 'react',
    icon: 'logos:react',
    favorite: false,
    desc: 'The library for web and native user interfaces',
    url: 'https://react.dev',
  },
  {
    name: 'Vite',
    value: 'vite',
    icon: 'logos:vitejs',
    favorite: true,
    desc: 'Next Generation Frontend Tooling',
    url: 'https://vitejs.dev',
  },
  {
    name: 'Node',
    value: 'node',
    icon: 'logos:nodejs-icon',
    favorite: false,
    desc: 'Cross-platform JavaScript runtime environment',
    url: 'https://nodejs.org',
  },
  {
    name: 'Prisma',
    value: 'prisma',
    icon: 'logos:prisma',
    favorite: true,
    url: 'https://prisma.io',
    desc: 'Next-generation Node.js and TypeScript ORM',
  },
  {
    name: 'MySQL',
    value: 'postgresql',
    icon: 'logos:mysql',
    favorite: false,
    desc: 'World\'s most popular open source database',
    url: 'https://www.mysql.com/',
  },
]
